# This pipeline runs unit tests for helium
#   when a PR occurs on https://github.com/microsoft/helium

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: HeliumKV

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- script: |
    cd docker
    sed s/@@1@@/$(intClientID)/ helium-release.env.template > helium-release.env.2
    sed s/@@2@@/$(intPassword)/ helium-release.env.2 > helium-release.env.3
    sed s/@@3@@/$(intTenantID)/ helium-release.env.3 > helium-release.env
    rm helium-release.env.2
    rm helium-release.env.3
    cd ..
    docker-compose build
    docker-compose up --abort-on-container-exit
  displayName: 'docker compose integration tests'
